name: Read External JSON
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - id: set_var
          run: |
            content=`cat ./example2-gitactions/dependencies.json`
            echo "::set-output name=jsonDep::$(jq -r '.dependencies[].repository' <<< "$content")"
        - name: print repo
          run: echo "${{fromJson(steps.set_var.outputs.jsonDep)[0]}}"


