name: Read External JSON
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - id: set_var
          run: |
            content=`cat ./example2-gitactions/dependencies.json`
            echo "$(jq -r '.dependencies[].repository' <<< "$content")" >> aux.txt
        - name: print repo
          run: cat aux.txt


